### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ripcord227** [atenadadkhah/dll-virus#1]
I'm trying to use this in something that im making lmao. When trying to run I get an error saying that I cant have a \ after System32 but, when I remove it I no longer get the error. I would like to test it out but yk.

**Comment by atenadadkhah** [comment]
If you want to test it you can change the extension .dll to something else like .txt and then see whether it's working correctly or not, but I've already tested it in my laptop (Not .dll extension) and it works correctly even that two back slashes are still after System32.
